### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#396]
## Description
As a user, I need to be able to easily find some documentation on the Powerup app so that I can understand what the app is all about.

### Update [Required]
- [x] [Adding some documentation of the Powerup app]
### Enhancement to Update [Optional]
- [x] [Adding related screenshots, video clips, tutorials]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
[3] hours

**Comment by nandini45** [comment]
@anubhavsingh16  
Can i work on it now?

**Comment by anubhavpulkit** [comment]
@nandini45 Are you working on PowerUp-iOS or you know about PowerUp project?

**Comment by nandini45** [comment]
@anubhavsingh16 
Yes I know about the project that is why I wanted to make the changes as readme is missing important details that's why

**Comment by anubhavpulkit** [comment]
You are working on PowerUp- Android version?

**Comment by nandini45** [comment]
no i am not working on it specifically. if u are talking about the proposal i worked on a brainstorming idea

**Comment by sunjunkie** [comment]
@anubhavsingh16 please check the remaining boxes in the description. Then I will,approve the issue.

**Comment by anubhavpulkit** [comment]
Done @sunjunkie Please approve this issue.

**Comment by sunjunkie** [comment]
You still have 1 remaining box to check. The issue is not fixed/done until a mentor approves.

**Comment by anubhavpulkit** [comment]
@sunjunkie Actually some days later you said that do not check "approved by 1 mentor" box that's why I cannot check that box.

**Comment by sunjunkie** [comment]
This issue is approved.

**Comment by anubhavpulkit** [comment]
Thank You @sunjunkie

**Comment by anubhavpulkit** [comment]
@nandini45 Any plans for this issue?

**Comment by anubhavpulkit** [comment]
@sunjunkie I want to work on this issue after about view controller issue.

**Comment by nandini45** [comment]
@anubhavsingh16  we can add screenshots of the application some major screenshots. we can add a workflow diagram then the screenshots.
workflow in sense what the user can do what sort of game he can play and so.
and then we can have a detailed description too.

**Comment by sunjunkie** [comment]
@anubhavsingh16 There are 2 high priority issues that must  be fixed before this one.

**Comment by sunjunkie** [comment]
It looks great.  But you reverted the 2nd question - "Why is Powerup needed?" :-)

So while you're at it: you repeat the same UIColor specifications 6 times.  It should be in a constant so any changes must done only once. Repeating code like that creates a chance for introducing a bug when making changes. Consider the following instead:
            
 ```
           let aboutColor = UIColor(red: 74/255, green: 160/255, blue: 166/255, alpha: 1.0)

            let attributesHeading: [NSAttributedString.Key : Any] = [
                .foregroundColor: aboutColor,
               .font: UIFont(name: "HelveticaNeue-Bold", size: 24)!
            ]
            let attributesText: [NSAttributedString.Key : Any] = [
               .foregroundColor: aboutColor,
               .font: UIFont(name: "HelveticaNeue", size: 20)!
            ]

            attributedString.addAttributes(attributesHeading, range: NSRange(location: 0, length: 8))
            attributedString.addAttributes(attributesText, range: NSRange(location: 10, length: 578))
            
           ...

```

**Comment by anubhavpulkit** [comment]
> @anubhavsingh16 There are 2 high priority issues that must be fixed before this one.

Ok @sunjunkie

**Comment by sunjunkie** [comment]
I put that comment above in the wrong place!

**Comment by anubhavpulkit** [comment]
Its ok @sunjunkie
